BulkRenamer: FileInfo.o BulkRenamer.o
	g++ -g -o BulkRenamer BulkRenamer.o FileInfo.o

FileInfo.o: FileInfo.h FileInfo.cpp
	g++ -g -c FileInfo.cpp

BulkRenamer.o: BulkRenamer.h BulkRenamer.cpp
	g++ -g -c BulkRenamer.cpp